name: Build and Test

on:
  push:
    branches: ["**"]
    tags-ignore: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run linter
        run: npm run lint
      - name: Run type checker
        run: npm run type-check
      # - name: Run tests
      #   run: npm run test
      - name: Build for Firefox
        run: npm run build:firefox
      - name: Clean up
        run: npm run clean
      - name: Build for Chromium
        run: npm run build:chromium
